name: Build

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: ossrh
        server-username: ${{ secrets.OSSRH_USERNAME }}
        server-password: ${{ secrets.OSSRH_PASSWORD }}
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: ${{ secrets.GPG_KEY_PASSPHRASE }}
        overwrite-settings: true

    - name: Check GPG
      run: |
        gpg --list-secret-keys

    - name: Build with Maven
      run: mvn -B clean package verify --file pom.xml
      env:
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_KEY_PASSPHRASE }}
        MAVEN_GPG_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
